=== DaScheid/jsr352/mybatch/src/main/resources/jobXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	targetNamespace="http://batch.jsr352/jsl" xmlns:jsl="http://batch.jsr352/jsl" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	jaxb:version="2.0">

	<xs:simpleType name="artifactRef">
		<xs:restriction base="xs:string" />
	</xs:simpleType>

	<xs:complexType name="Job">
		<xs:sequence>
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
			<xs:element name="listeners" type="jsl:Listeners" minOccurs="0" maxOccurs="1" />
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="decision" type="jsl:Decision" />
				<xs:element name="flow" type="jsl:Flow" />
				<xs:element name="split" type="jsl:Split" />
				<xs:element name="step" type="jsl:Step" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:ID" />
		<xs:attribute name="parent" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:element name="job" type="jsl:Job" />

	<xs:complexType name="Listener">
		<xs:sequence>
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="ref" use="required" type="jsl:artifactRef" />
	</xs:complexType>

	<xs:complexType name="Split">
		<xs:sequence>
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
			<xs:element name="flow" type="jsl:Flow" minOccurs="0" maxOccurs="unbounded"/>
			<xs:group ref="jsl:ControlElements" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:ID" />
		<xs:attribute name="next" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="Flow">
		<xs:sequence>
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="decision" type="jsl:Decision" />
				<xs:element name="step" type="jsl:Step" />
			</xs:choice>
			<xs:group ref="jsl:ControlElements" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:ID" />
		<xs:attribute name="next" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:group name="ControlElements">
		<!-- I guess no point being strict if you don't want to group like elements. -->
		<xs:choice>
			<xs:element name="end" type="jsl:End" />
			<xs:element name="fail" type="jsl:Fail" />
			<xs:element name="next" type="jsl:Next" />
			<xs:element name="stop" type="jsl:Stop" />
		</xs:choice>
	</xs:group>

	<xs:complexType name="Decision">
		<xs:sequence>
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
			<xs:group ref="jsl:ControlElements" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:ID" />
		<xs:attribute name="ref" use="required" type="jsl:artifactRef" />
	</xs:complexType>

	<xs:attributeGroup name="TerminatingAttributes">
		<xs:attribute name="on" use="required" type="xs:string" />
		<xs:attribute name="exit-status" use="optional" type="xs:string" />
	</xs:attributeGroup>

	<xs:complexType name="Fail">
		<xs:attributeGroup ref="jsl:TerminatingAttributes" />
	</xs:complexType>

	<xs:complexType name="End">
		<xs:attributeGroup ref="jsl:TerminatingAttributes" />
	</xs:complexType>

	<xs:complexType name="Stop">
		<xs:attributeGroup ref="jsl:TerminatingAttributes" />
		<xs:attribute name="restart" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="Next">
		<xs:attribute name="on" use="required" type="xs:string" />
		<xs:attribute name="to" use="required" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="Step">
		<xs:sequence>
			<xs:element name="partition" type="jsl:Partition" minOccurs="0" maxOccurs="1" />
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
			<xs:element name="listeners" type="jsl:Listeners" minOccurs="0" maxOccurs="1" />
			<xs:choice>
				<xs:element name="batchlet" type="jsl:Batchlet" />
				<xs:element name="chunk" type="jsl:Chunk" />
			</xs:choice>
			<xs:group ref="jsl:ControlElements" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:ID" />
		<xs:attribute name="start-limit" use="optional" type="xs:string" />
		<xs:attribute name="allow-start-if-complete" use="optional" type="xs:string" />
		<xs:attribute name="next" use="optional" type="xs:string" />
		<xs:attribute name="abstract" use="optional" type="xs:string" />
		<xs:attribute name="parent" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="Batchlet">
		<xs:sequence>
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="ref" use="required" type="jsl:artifactRef" />
	</xs:complexType>

	<xs:complexType name="Chunk">
		<xs:sequence>
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="reader" use="required" type="xs:string" />
		<xs:attribute name="processor" use="required" type="xs:string" />
		<xs:attribute name="writer" use="required" type="xs:string" />
		<xs:attribute name="checkpoint-policy" use="optional" type="xs:string" default="item" />
		<xs:attribute name="commit-interval" use="optional" type="xs:string" default="10" />
		<xs:attribute name="buffer-reads" use="optional" type="xs:string" default="true" />
		<xs:attribute name="chunk-size" use="required" type="xs:string" />
		<xs:attribute name="skip-limit" use="optional" type="xs:string" />
		<xs:attribute name="retry-limit" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="Property">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="required" />
		<xs:attribute name="applyToPartition" type="xs:string" use="optional" />
		<xs:attribute name="applyTo" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="Properties">
		<xs:sequence>
			<xs:element name="property" type="jsl:Property" maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Listeners">
		<xs:sequence>
			<xs:element name="listener" type="jsl:Listener" maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Partition">
		<xs:sequence>
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
		    <xs:element name="algorithm" type="jsl:Algorithm" minOccurs="0" maxOccurs="1" />
		    <xs:group ref="jsl:ConcurrencyElements" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="instances" use="optional" type="xs:string" />
		<xs:attribute name="threads" use="optional" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="Algorithm">
		<xs:sequence>
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="ref" use="required" type="jsl:artifactRef" />
	</xs:complexType>
	
	<xs:complexType name="Collector">
		<xs:sequence>
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="ref" use="required" type="jsl:artifactRef" />
	</xs:complexType>

	<xs:complexType name="Analyzer">
		<xs:sequence>
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="ref" use="required" type="jsl:artifactRef" />
	</xs:complexType>

	<xs:complexType name="LogicalTXSynchronization">
		<xs:sequence>
			<xs:element name="properties" type="jsl:Properties" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="ref" use="required" type="jsl:artifactRef" />
	</xs:complexType>

	<xs:group name="ConcurrencyElements">
		<xs:choice>
			<xs:element name="collector" type="jsl:Collector" />
			<xs:element name="analyzer" type="jsl:Analyzer" />
			<xs:element name="logicalTXSynchronization " type="jsl:LogicalTXSynchronization" />
		</xs:choice>
	</xs:group>

</xs:schema>

=== DaScheid/jsr352/test-apps/flow/src/main/resources/META-INF/batch-jobs/flow.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
~ JBoss, Home of Professional Open Source.
~ Copyright 2013, Red Hat, Inc., and individual contributors
~ as indicated by the @author tags. See the copyright.txt file in the
~ distribution for a full listing of individual contributors.
~
~ This is free software; you can redistribute it and/or modify it
~ under the terms of the GNU Lesser General Public License as
~ published by the Free Software Foundation; either version 2.1 of
~ the License, or (at your option) any later version.
~
~ This software is distributed in the hope that it will be useful,
~ but WITHOUT ANY WARRANTY; without even the implied warranty of
~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
~ Lesser General Public License for more details.
~
~ You should have received a copy of the GNU Lesser General Public
~ License along with this software; if not, write to the Free
~ Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
~ 02110-1301 USA, or see the FSF site: http://www.fsf.org.
-->

<job id="job1" xmlns="http://xmlns.jcp.org/xml/ns/javaee"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://java.net/projects/jbatch/sources/jsr-352-git-repository/content/JSR352.JobXML.Model/src/main/resources/jobXML.xsd">

    <properties>
        <property name="job-prop" value="job-prop"></property>
        <property name="job-prop-2" value="job-prop-2"></property>
    </properties>
    <listeners>
        <listener ref="L1">
            <properties>
                <property name="listener-prop" value="listener-prop"></property>
                <property name="reference-job-prop" value="#{jobProperties['job-prop']}"></property>
                <property name="reference-job-param" value="#{jobParameters['job-param']}"></property>
                <property name="reference-system-property" value="#{systemProperties['java.version']}"></property>
            </properties>
        </listener>
        <listener ref="L2"></listener>
    </listeners>


    <flow id="flow1" next="step4">
        <step id="step1" next="step2">
            <properties>
                <property name="step-prop" value="step-prop"></property>
                <!-- same property name as in job, to test property resolution precedence -->
                <property name="job-prop-2" value="step-prop-2"></property>
            </properties>
            <batchlet ref="Batchlet1">
            </batchlet>
        </step>

        <step id="step3">
            <batchlet ref="Batchlet1">
            </batchlet>
            <end on="*" exit-status="done"></end>
        </step>

        <step id="step2">
            <batchlet ref="Batchlet1">
            </batchlet>
            <stop on="xyzz" exit-status="stopped" restart="false"/>
            <!-- should not reach here -->
            <fail on="abcd" exit-status="failed"/>
            <!-- should not reach here -->
            <end on="12345" exit-status="done"/>
            <!-- should not reach here -->
            <next on="aaa" to="step1"/>
            <!-- should not reach here -->
            <next on="*" to="decision1"></next>
        </step>

        <decision id="decision1" ref="Decider1">
            <properties>
                <property name="decision-prop" value="decision-prop"></property>
                <property name="reference-job-prop" value="#{jobProperties['job-prop']}"></property>
                <property name="reference-step-prop" value="#{jobProperties['step-prop']}"></property>
                <property name="reference-system-prop" value="#{systemProperties['java.version']}"></property>
                <property name="reference-job-param" value="#{jobParameters['job-param']}"></property>
            </properties>
            <next on="aaa" to="step1"></next>
            <!-- should not reach here -->
            <next on="next" to="step3"></next>
            <!-- "next" is the value returned from Decider1.decide() -->
            <end on="*" exit-status="done"></end>
        </decision>
    </flow>

    <step id="step4">
        <batchlet ref="Batchlet1">
            <properties>
                <property name="batchlet-prop" value="batchlet-prop"></property>
                <property name="reference-job-prop" value="#{jobProperties['job-prop']}"></property>
                <property name="reference-system-prop" value="#{systemProperties['java.version']}"></property>
                <property name="reference-job-param" value="#{jobParameters['job-param']}"></property>
            </properties>
        </batchlet>
    </step>

</job>

=== DaScheid/jsr352/test-apps/loadBatchXml/src/main/resources/META-INF/batch-jobs/batchlet1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
~ JBoss, Home of Professional Open Source.
~ Copyright 2013, Red Hat, Inc., and individual contributors
~ as indicated by the @author tags. See the copyright.txt file in the
~ distribution for a full listing of individual contributors.
~
~ This is free software; you can redistribute it and/or modify it
~ under the terms of the GNU Lesser General Public License as
~ published by the Free Software Foundation; either version 2.1 of
~ the License, or (at your option) any later version.
~
~ This software is distributed in the hope that it will be useful,
~ but WITHOUT ANY WARRANTY; without even the implied warranty of
~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
~ Lesser General Public License for more details.
~
~ You should have received a copy of the GNU Lesser General Public
~ License along with this software; if not, write to the Free
~ Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
~ 02110-1301 USA, or see the FSF site: http://www.fsf.org.
-->

<job id="job1" xmlns="http://batch.jsr352/jsl"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://batch.jsr352/jsl http://java.net/projects/jbatch/sources/jsr-352-git-repository/content/JSR352.JobXML.Model/src/main/resources/jobXML.xsd">

    <properties>
        <property name="job-prop" value="job-prop"></property>
        <property name="job-prop-2" value="job-prop-2"></property>
    </properties>
    <listeners>
        <listener ref="L1">
            <properties>
                <property name="listener-prop"             value="listener-prop"></property>
                <property name="reference-job-prop"        value="#{jobProperties['job-prop']}"></property>
                <property name="reference-job-param"       value="#{jobParameters['job-param']}"></property>
                <property name="reference-system-property" value="#{systemProperties['java.version']}"></property>
            </properties>
        </listener>
        <listener ref="L2"></listener>
    </listeners>

    <step id="step1" next="step2">
        <properties>
            <property name="step-prop" value="step-prop"></property>
            <!-- same property name as in job, to test property resolution precedence -->
            <property name="job-prop-2" value="step-prop-2"></property>
        </properties>
        <listeners>
            <listener ref="L3">
                <properties>
                    <property name="listener-prop"       value="step-listener-prop"></property>
                    <property name="reference-job-prop"  value="#{jobProperties['job-prop']}"></property>
                    <property name="reference-step-prop" value="#{jobProperties['step-prop']"></property>
                    <property name="reference-job-prop-2" value="#{jobProperties['job-prop-2']}"></property>
                </properties>
            </listener>
            <listener ref="L4"></listener>
        </listeners>
        <batchlet ref="Batchlet1">
        </batchlet>
    </step>

    <step id="step3">
        <batchlet ref="Batchlet1">
        </batchlet>
        <end on="*" exit-status="done"></end>
    </step>

    <step id="step2">
        <batchlet ref="Batchlet1">
        </batchlet>
        <next on="*" to="step3"></next>
    </step>

</job>

=== DaScheid/jsr352/test-apps/split/src/main/resources/META-INF/batch-jobs/split.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
~ JBoss, Home of Professional Open Source.
~ Copyright 2013, Red Hat, Inc., and individual contributors
~ as indicated by the @author tags. See the copyright.txt file in the
~ distribution for a full listing of individual contributors.
~
~ This is free software; you can redistribute it and/or modify it
~ under the terms of the GNU Lesser General Public License as
~ published by the Free Software Foundation; either version 2.1 of
~ the License, or (at your option) any later version.
~
~ This software is distributed in the hope that it will be useful,
~ but WITHOUT ANY WARRANTY; without even the implied warranty of
~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
~ Lesser General Public License for more details.
~
~ You should have received a copy of the GNU Lesser General Public
~ License along with this software; if not, write to the Free
~ Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
~ 02110-1301 USA, or see the FSF site: http://www.fsf.org.
-->

<job id="job1" xmlns="http://xmlns.jcp.org/xml/ns/javaee"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://java.net/projects/jbatch/sources/jsr-352-git-repository/content/JSR352.JobXML.Model/src/main/resources/jobXML.xsd">

    <properties>
        <property name="job-prop" value="job-prop"></property>
        <property name="job-prop-2" value="job-prop-2"></property>
    </properties>

    <split id="split1" next="decision1">
        <properties>
            <property name="split-prop" value="split-prop"/>
        </properties>
        <flow id="flow1">
            <properties>
                <property name="flow-prop" value="flow-prop"/>
            </properties>
            <step id="step11" next="step12">
                <properties>
                    <property name="step-prop" value="step-prop"></property>
                </properties>
                <batchlet ref="Batchlet1">
                    <properties>
                        <property name="reference-flow-prop" value="#{jobProperties['flow-prop']}"/>
                        <property name="reference-split-prop" value="#{jobProperties['split-prop']}"/>
                    </properties>
                </batchlet>
            </step>

            <step id="step12">
                <batchlet ref="Batchlet1"/>
            </step>
        </flow>

        <flow id="flow2">
            <step id="step21">
                <batchlet ref="Batchlet1"/>
                <next on="*" to="step22"/>
            </step>
            <step id="step22">
                <batchlet ref="Batchlet1"/>
            </step>
        </flow>
    </split>

    <decision id="decision1" ref="Decider2">
        <!-- Decider2 sets exit status to "next", thus directing the job to step3 -->
        <next on="next" to="step3" />
    </decision>
    
    <step id="step3">
        <batchlet ref="Batchlet1"/>
    </step>

</job>
